CXX = g++
CXXFLAGS = -g -o0 --std=c++11

longest_increasing_subsequece_DP: longest_increasing_subsequence_DP.o
	$(CXX) $(CXXFLAGS) longest_increasing_subsequence_DP.cpp -o longest_increasing_subsequence_DP.exe

minimum_step_to_one_DP: minimum_step_to_one_DP.o
	$(CXX) $(CXXFLAGS) minimum_step_to_one_DP.cpp -o minimum_step_to_one_DP.exe

