
CXX = g++
CXXFLAGS = -g -o0 --std=c++11

printing_binary_tree_vertically_hash: printing_binary_tree_vertically_hash.o
	$(CXX) $(CXXFLAGS) printing_binary_tree_vertically_hash.cpp -o printing_binary_tree_vertically_hash.exe

find_if_two_in_array_add_up_hash: find_if_two_in_array_add_up_hash.o
	$(CXX) $(CXXFLAGS) find_if_two_in_array_add_up_hash.cpp -o find_if_two_in_array_add_up_hash.exe

group_multiple_occurrences_hash: group_multiple_occurrences_hash.o
	$(CXX) $(CXXFLAGS) group_multiple_occurrences_hash.cpp -o group_multiple_occurrences_hash.exe

find_symmetrical_pairs_hash: find_symmetrical_pairs_hash.o
	$(CXX) $(CXXFLAGS) find_symmetrical_pairs_hash.cpp -o find_symmetrical_pairs_hash.exe

find_missing_elements_in_range_hash: find_missing_elements_in_range_hash.o
	$(CXX) $(CXXFLAGS) ffind_missing_elements_in_range_hash.cpp -o find_missing_elements_in_range_hash.exe
clean:
	rm *.exe *.o