CXX = g++
CXXFLAGS = -g -o0 --std=c++11

longest_increasing_subsequece_DP: longest_increasing_subsequence_DP.o
	$(CXX) $(CXXFLAGS) longest_increasing_subsequence_DP.cpp -o longest_increasing_subsequence_DP.exe

longest_common_subsequence_DP: longest_common_subsequence_DP.o
	$(CXX) $(CXXFLAGS) longest_common_subsequence_DP.cpp -o longest_common_subsequence_DP.exe

minimum_step_to_one_DP: minimum_step_to_one_DP.o
	$(CXX) $(CXXFLAGS) minimum_step_to_one_DP.cpp -o minimum_step_to_one_DP.exe

word_break_DP: word_break_DP.o
	$(CXX) $(CXXFLAGS) word_break_DP.cpp -o word_break_DP.exe

longest_palindrome_DP: longest_palindrome_DP.o
	$(CXX) $(CXXFLAGS) longest_palindrome_DP.cpp -o longest_palindrome_DP.exe

word_break_DP1: word_break_DP1.o
	$(CXX) $(CXXFLAGS) word_break_DP1.cpp -o word_break_DP1.exe
	
clean:
	rm *.exe *.o