CXX = g++
CXXFLAGS = -g -o0 --std=c++11

strcpy: strcpy.o
	$(CXX) $(CXXFLAGS) strcpy.cpp -o strcpy.exe

longest_substring_without_repeat: longest_substring_without_repeat.o
	$(CXX) $(CXXFLAGS) longest_substring_without_repeat.cpp -o longest_substring_without_repeat.exe

clean:
	rm *.exe *.o