mergesort: mergesort.o
	g++ -g -o0 -Wall -Werror -std=c++11 mergesort.cpp -o mergesort.exe

insertionsort: insertionsort.o
	g++ -g -o0 -Wall -Werror insertionsort.cpp -o insertionsort.exe

quicksort: quicksort.o
	gcc -g -o0 -Wall -Werror quicksort.cpp -o quicksort.exe

selectionsort: selectionsort.o
	g++ -g -o0 -Wall -Werror selectionsort.cpp -o selectionsort.exe
	
clean:
	rm *.exe *.o